apps/api/geodata/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import viewsets

router = routers.DefaultRouter()
router.register(r'departamentos', viewsets.DepartamentoViewSet)
router.register(r'municipios', viewsets.MunicipioViewSet)
router.register(r'localidad', viewsets.LocalidadViewSet)
router.register(r'departamentos_', viewsets.DepartamentoBasicInfoViewSet)
router.register(r'municipios_', viewsets.MunicipioBasicInfoViewSet)

urlpatterns = [
    url(r'^viewsets/', include(router.urls)),
]

apps/geodata/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^subir-barrios/',
        views.BarriosUploadView.as_view(),
        name='subir_barrios'),

    url(r'^subir-corregimientos/',
        views.CorregimientosUploadView.as_view(),
        name='subir_corregimientos'),

    url(r'^subir-votantes/',
        views.VotanteUploadView.as_view(),
        name='subir_votante'),

    # origenes de datos

    url(r'^departamentos/',
        views.DepartamentoListView.as_view(),
        name='departamentos'),

    url(r'^detalle_departamento/(?P<pk>\d+)/',
        views.DepartamentoDetalleListView.as_view(),
        name='detalle_departamento'),

    url(r'^municipios_departamento/(?P<pk>\d+)/',
        views.MunicipioDepartamentoView.as_view(),
        name='municipios_departamento'),

    url(r'^corregimientos_departamento/(?P<pk>\d+)/',
        views.CorregimientosDepartamentoView.as_view(),
        name='corregimientos_departamento'
        ),

    url(r'^detalle_municipio/(?P<pk>\d+)/',
        views.MunicipioDetailView.as_view(),
        name='detalle_municipio'),

    url(r'^corregimientos_municipio/(?P<pk>\d+)/',
        views.CorregimientosMunicipioView.as_view,
        name='corregimientos_municipio'),

    url(r'^barrios_municipio/(?P<pk>\d+)/',
        views.BarriosMunicipio.as_view(),
        name='barrios_municipio'),

    url(r'^lista_votantes_municipio/(?P<pk>\d+)/',
        views.ListaVotantesMunicipioListView.as_view(),
        name='lista_votantes_municipio'),

    url(r'^lista_votantes_contactados_municipio/(?P<pk>\d+)/',
        views.VotantesContactadosMunicipioListView.as_view(),
        name='lista_votantes_contactados_municipio'),

    url(r'^lista_votantes_no_contactados_municipio/(?P<pk>\d+)/',
        views.VotantesNoContactadosMunicipioListView.as_view(),
        name='lista_votantes_no_contactados_municipio'),

]

apps/third_party_apps/fcm/urls.py
from django.conf.urls import url

from . import views

urlpatterns = (
    url(r'^devices/$', views.DeviceList.as_view(), name='device_list'),
    url(r'^devices/(?P<pk>[0-9]+)/$', views.DeviceDetail.as_view(),
        name='device_detail'),
    url(r'^send/$', views.FCMList.as_view(), name='fcm_send'),
)

project/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from .settings import base
from django.contrib import admin
from apps.utils import errors
from .settings import local

urlpatterns = [

    url(r'^elixir_master/', admin.site.urls),
    #frameworks and plugins
    # smart selects
    url(r'^chaining/', include('smart_selects.urls')),
    # rest auth
    url(r'^rest-auth/', include('rest_auth.urls')),
    # fcm
    url(r'^fcm/', include('apps.third_party_apps.fcm.urls')),
    # api
    url(r'^api/', include('apps.api.urls', namespace='api')),
    # apps 
    url(r'^app/', include('apps.app.urls', namespace='app')),
    url(r'^', include('apps.main.urls', namespace='main')),
    url(r'^geodata/', include('apps.geodata.urls', namespace='geodata')),
    url(r'^votantes/', include('apps.votantes.urls', namespace='votantes')),
    url(r'^reportes/', include('apps.reportes.urls', namespace='reportes')),
    

] + static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

if local.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

handler400 = errors.error400
handler403 = errors.error403
handler404 = errors.error404
handler500 = errors.error500

apps/geodata/models.py
from django.db import models
from datetime import datetime
# Create your models here.
from django.contrib.auth.models import User
from django import urls
from django.db.models import Q
from smart_selects.db_fields import ChainedForeignKey

from . import constants
from apps.third_party_apps.gis.db import models

# Create your models here.
from apps.utils.shortcuts import get_object_or_none, remove_accent
from apps.votantes.models import Votante, LiderElectoral


class Base(models.Model):
    nombre = models.CharField(max_length=255)
    coordenadas = models.PointField(blank=True, null=True)
    area = models.PolygonField(blank=True, null=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.nombre

    def get_longitude(self):
        return self.get_data_point()[0] if self.coordenadas is not None else 0

    def get_latitude(self):
        return self.get_data_point()[1] if self.coordenadas is not None else 0

    def get_data_point(self):
        return [coord for coord in self.coordenadas]


class BaseNombreVotantes(models.Model):
    nombre = models.CharField(max_length=50)
    registro = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.nombre


class ContarVotosNegativos(object):
    attr_query = None

    def votos_reales(self):
        return Votante.objects.filter(**constants.get_good_votes(
            self.attr_query,
            self
        ))

    def cantidad_votos_reales(self):
        return self.votos_reales().count()


class Region(Base):
    class Meta:
        verbose_name = 'Region'
        verbose_name_plural = 'Regiones'

    def get_departamentos(self):
        return Departamento.objects.filter(region=self)


class Departamento(Base):
    numero = models.CharField(max_length=3, blank=True, null=True)
    region = models.ForeignKey(Region, blank=True, null=True)
    area_total = models.DecimalField(max_digits=30, decimal_places=15, blank=True, null=True)
    hectareas = models.DecimalField(max_digits=30, decimal_places=15, blank=True, null=True)
    perimetro = models.DecimalField(max_digits=30, decimal_places=15, blank=True, null=True)
    area = models.GeometryField(blank=True, null=True)
    imagen = models.ImageField(upload_to='departamentos', blank=True, null=True)

    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'
        ordering = ['nombre']

    def municipios_total(self):
        return "\n".join(['{}. '.format(p.nombre) for p in self.get_municipios()])

    def get_municipios(self):
        return Municipio.objects.filter(departamento=self)

    def municipios(self):
        return self.get_municipios().count()

    def get_corregimientos(self):
        return Corregimiento.objects.filter(municipio__departamento=self)

    def votantes(self):
        return Votante.objects.filter(municipio__departamento=self)

    def cantidad_votantes(self):
        return self.votantes().count()

    def puestos_votacion(self):
        return PuestoVotacion.objects.filter(municipio__departamento=self)

    def cantidad_puestos_votacion(self):
        return self.puestos_votacion().count()

    def mesas(self):
        return MesaVotacion.objects.filter(puesto_votacion__municipio__departamento=self)

    def cantidad_mesas(self):
        return self.mesas().count()

    @classmethod
    def search(cls, name):
        return get_object_or_none(
            cls,
            nombre=remove_accent(name.upper())
        )

    def get_kwargs(self):
        return {
            'pk': self.pk
        }

    def get_absolute_url(self):
        return urls.reverse_lazy('geodata:detalle_departamento', kwargs=self.get_kwargs())

    def get_municipios_url(self):
        return urls.reverse_lazy('geodata:municipios_departamento', kwargs=self.get_kwargs())

    def get_corregimientos_url(self):
        return urls.reverse_lazy('geodata:corregimientos_departamento', kwargs=self.get_kwargs())

    @staticmethod
    def get_votantes_filter(**kwargs):
        return Votante.objects.filter(**kwargs)

    def get_votantes_senado(self):
        return self.get_votantes_filter(**{
            'municipio__departamento': self,
            'corregimiento__isnull': True,
            'votaria_senado': True
        })

    def get_votantes_senado_count(self):
        return self.get_votantes_senado().count()

    def get_votantes_camara(self):
        return self.get_votantes_filter(**{
            'municipio__departamento': self,
            'corregimiento__isnull': True,
            'votaria_camara': True
        })

    def get_votantes_camara_count(self):
        return self.get_votantes_camara().count()

    def get_votantes_presidencia(self):
        return self.get_votantes_filter(**{
            'municipio__departamento': self,
            'corregimiento__isnull': True,
            'votaria_presidencia': True
        })

    def get_votantes_presidencia_count(self):
        return self.get_votantes_presidencia().count()

    def get_votantes_contactados(self):
        return self.get_votantes_filter(**{
            'municipio__departamento': self,
            'corregimiento__isnull': True,
            'contactado': True
        })

    def get_votantes_contactados_count(self):
        return self.get_votantes_contactados().count()

    def get_votantes_no_contactados(self):
        return self.get_votantes_filter(**{
            'municipio__departamento': self,
            'corregimiento__isnull': True,
            'contactado': False
        })

    def get_votantes_no_contactados_count(self):
        return self.get_votantes_no_contactados().count()

    def get_votantes_sin_cedula(self):
        return self.get_votantes_filter(**{
            'cedula__exact': '',
            'municipio__departamento': self
        })

    def get_votantes_sin_cedula_count(self):
        return self.get_votantes_sin_cedula().count()

    def get_simpatizantes(self):
        return self.get_votantes_filter(**{
            'tipo_votante__icontains': 'SIMPATIZANTE',
            'municipio__departamento': self
        })

    def get_referidos(self):
        return self.get_votantes_filter(**{
            'tipo_votante__icontains': 'REFERIDO',
            'municipio__departamento': self
        })

    def get_voluntario(self):
        return self.get_votantes_filter(**{
            'tipo_votante__icontains': 'VOLUNTARIO',
            'municipio__departamento': self
        })

    def get_nuevos_hoy(self):
        date = datetime.now().date()
        return self.get_votantes_filter(**{
            'municipio__departamento': self,
            'creacion__day': date.day,
            'creacion__month': date.month,
            'creacion__year': date.year
        })


class Municipio(Base):
    nombre_cab = models.CharField(max_length=255, blank=True, null=True)
    region = models.ForeignKey(Region, blank=True, null=True)
    departamento = models.ForeignKey(Departamento, blank=True, null=True)
    ciudad = models.BooleanField(default=False, editable=False)
    organizado_localidad = models.BooleanField(default=False)
    capital_departamental = models.BooleanField(default=False)
    contiene_comunas = models.BooleanField(default=False)
    contiene_upz = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Municipio'
        verbose_name_plural = 'Municipios'
        ordering = ['nombre', 'departamento']

    def get_corregimientos(self):
        return Corregimiento.objects.filter(municipio=self)

    def get_votantes_filter(self, **kwargs):
        return Votante.objects.filter(**kwargs)

    def get_votantes_senado(self):
        return self.get_votantes_filter(**{
            'municipio': self,
            'corregimiento__isnull': True,
            'votaria_senado': True
        })

    def get_votantes_senado_count(self):
        return self.get_votantes_senado().count()

    def get_votantes_camara(self):
        return self.get_votantes_filter(**{
            'municipio': self,
            'corregimiento__isnull': True,
            'votaria_camara': True
        })

    def get_votantes_camara_count(self):
        return self.get_votantes_camara().count()

    def get_votantes_presidencia(self):
        return self.get_votantes_filter(**{
            'municipio': self,
            'corregimiento__isnull': True,
            'votaria_presidencia': True
        })

    def get_votantes_presidencia_count(self):
        return self.get_votantes_presidencia().count()

    def get_votantes_contactados(self):
        return self.get_votantes_filter(**{
            'municipio': self,
            'corregimiento__isnull': True,
            'contactado': True
        })

    def get_votantes_contactados_count(self):
        return self.get_votantes_contactados().count()

    def get_votantes_no_contactados(self):
        return self.get_votantes_filter(**{
            'municipio': self,
            'corregimiento__isnull': True,
            'contactado': False
        })

    def get_votantes_no_contactados_count(self):
        return self.get_votantes_no_contactados().count()

    def get_votantes_sin_cedula(self):
        return self.get_votantes_filter(**{
            'cedula__exact': '',
            'municipio': self,
        })

    def get_votantes_sin_cedula_count(self):
        return self.get_votantes_sin_cedula().count()

    def get_cantidad_corregimientos(self):
        return self.get_corregimientos().count()

    def get_municipios(self):
        return Municipio.objects.filter(departamento=self)

    def get_localidades(self):
        return Localidad.objects.filter(municipio=self)

    def get_upz(self):
        return Upz.objects.filter(localidad__municipio=self)

    def get_barrios(self):
        return Barrio.objects.filter(municipio=self)

    def votantes(self):

apps/api/geodata/views.py
from rest_framework import generics, viewsets
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from . import serializers

templates/apps/geodata/departamentos/departamentos.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block titulo %}
    Departamentos
{% endblock %}

{% block main %}

    <div class="container">

        <div class="block-header">
            <div align="center"><h2>DEPARTAMENTOS</h2></div>
        </div>

        {% for departamento in object_list %}
            {% if forloop.first %}
                <div class="row">
            {% endif %}
        <div class="col-md-3">
            <!-- Blog Posts -->
            <div class="card blog-post">

                {% if departamento.imagen %}
                         <img src="{{ departamento.imagen.url }}" class="img-responsive" alt="">
                    {% else %}
                         <img src="{% static 'img/demo/map.png' %} " class="img-responsive" alt="">
                {% endif %}

                <a class="card-header ch-alt" href="widgets.html">
                    <h2>{{ departamento.nombre|truncatechars:15 }}</h2>
                    <h5>Municipios: {{ departamento.get_municipios.count }} </h5>
                    <h5>Cantidad de votos: {{ departamento.votantes.count }}</h5>
                </a>

                <div class="card-body card-padding">
                    <div align="center"><a href="{{ departamento.get_absolute_url }}"
                                           class="btn bgm-purple btn-xs"><i class="zmdi zmdi-eye"></i> Ver</a>
                    </div>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:4 %}
            </div>
            <div class="row">
        {% endif %}
        {% if forloop.last %}
            </div>
        {% endif %}

        {% endfor %}
    </div>

{% endblock %}

templates/apps/geodata/departamentos/detalle_departamento.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block titulo %}
    Detalle del departamento {{ departamento.nombre }}
{% endblock %}

{% block main %}

    <div class="container">

        <div class="block-header">
                <div align="center" ><h2>DEPARTAMENTO  DE {{ departamento.nombre }}</h2></div>
        </div>

        <div class="card">

                <div class="card-body ">
                    <div class="row">
                        <div class="col-md-8">
                            <!--Google map-->
                    <div id="map-container" class="z-depth-1" style="height: 500px"></div>
                        </div>
                        <div class="col-md-4">
                            <div class="row">
                                <div class="col-md-12">
                                    <h1>{{ departamento.nombre }}</h1>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <h2>Municipios: {{ departamento.get_municipios.count }}</h2>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <h2>Corregimientos: {{ departamento.get_corregimientos.count }}</h2>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <h2>Votos: {{ departamento.votantes.count }}</h2>
                                </div>
                            </div>
                             <div class="row">
                                 <div class="col-md-12">
                                    <div align="center"><a href="{{ departamento.get_municipios_url }}" class="btn bgm-purple waves-effect">Ver Municipios </a></div>
                                </div>
                            </div>
                            <br>
                             <div class="row">
                                 <div class="col-md-12">
                                 <div align="center"> <a href="{% url 'geodata:departamentos' %}" class="btn bgm-purple waves-effect">Volver a departamentos </a></div>
                                </div>
                            </div>

                        </div>
                    </div>
              </div>
            </div>

    </div>

     <div class="container">
        <div align="center">
            <h2>
                LISTA DE VOTANTES DEL DEPARTAMENTO DE   {{ departamento.nombre }}
            </h2>
        </div>
    </div>


    <div class="card">
        <div class="card-body">

            <div class="row">
                <div class="col-md-12" style="overflow-x: auto;">
                    {% include 'utils/paginator.html' %}
                    <table class="table table-stripped table-hover table-responsive table-bordered">
                        <thead>
                        <tr>
                            <th class="text-center">Cedula</th>
                            <th class="text-center">Nombre</th>
                            <th class="text-center">Departamento</th>
                            <th class="text-center">Municipio / Corregimiento</th>
                            <th class="text-center">Localidad / Barrio</th>
                            <th class="text-center">Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for votante in object_list %}
                            <tr>
                                <td class="text-center">
                                    {% if votante.cedula %}
                                        {{ votante.cedula }}
                                    {% else %}
                                        <i class="fa fa-close text-danger"></i>
                                    {% endif %}
                                </td>
                                <td class=text-center">
                                    {% if votante.nombre %}
                                        {{ votante.nombre }}
                                    {% else %}
                                        <i class="fa fa-close text-danger"></i>
                                    {% endif %}
                                </td>
                                <td class=text-center">
                                    {% if votante.departamento %}
                                        {{ votante.departamento }}
                                    {% else %}
                                        <i class="fa fa-close text-danger"></i>
                                    {% endif %}
                                </td>
                                <td class=text-center">
                                    {% if votante.municipio %}
                                        {{ votante.municipio }}
                                    {% elif votante.corregimiento %}
                                        {{ votante.municipio }} / {{ votante.corregimiento }}
                                    {% else %}
                                        <i class="fa fa-close text-danger"></i>
                                    {% endif %}
                                </td>
                                <td class=text-center">
                                    {% if votante.barrio %}
                                        {{ votante.barrio }} /  {{ votante.localidad }}
                                    {% else %}
                                        <i class="fa fa-close text-danger"></i>
                                    {% endif %}


                                </td>
                                <td class=text-center">
                                    <a href="{{votante.get_absolute_url}}"
                                       class="btn btn-primary waves-effect btn-xs"
                                       data-toggle="tooltip" data-placement="top" title=""
                                       data-original-title="Ver perfil">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                    {% include 'utils/paginator.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {% load staticfiles %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.css">



    <script>
        var map;
        function initMap() {
            map = new google.maps.Map(document.getElementById('map-container'), {
                zoom: 6,
                center: {lat: 3.8519738, lng: -73.6671921}
            });

            // NOTE: This uses cross-domain XHR, and may not work on older browsers.
            map.data.loadGeoJson(
                'http://localhost:8000/api/geodata/viewsets/departamentos/'+{{ departamento.id }}+'/?format=json');
            map.data.setStyle({
                fillColor: 'red',
                strokeWeight: 1
            });
            map.addListener('click', showArrays);
        }

        /** @this {google.maps.Polygon} */
        function showArrays(event) {
            // Since this polygon has only one path, we can call getPath() to return the
            // MVCArray of LatLngs.
            var vertices = this.getPath();

            var contentString = '<b>Departamento de {{ departamento.nombre }}</b><br>' +
                'Ubicacion: <br>' + event.latLng.lat() + ',' + event.latLng.lng() +
                '<br>';

            // Iterate over the vertices.
            for (var i = 0; i < vertices.getLength(); i++) {
                var xy = vertices.getAt(i);
                contentString += '<br>' + 'Coordenadas ' + i + ':<br>' + xy.lat() + ',' +
                    xy.lng();
            }

            // Replace the info window's content and position.
            infoWindow.setContent(contentString);
            infoWindow.setPosition(event.latLng);

            infoWindow.open(map);
        }

    </script>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCZKP0IwBnUJ7zh_384tkLqlMMZF0B-vY4&callback=initMap">
    </script>


{% endblock %}

templates/apps/geodata/departamentos/municipios_departamento.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block titulo %}
    Municipios de {{ departamento.nombre }}
{% endblock %}

{% block main %}
    <div class="container">
        <div align="center"><h2>MUNICIPIOS DE {{ departamento.nombre }}</h2></div>
    </div>
    <div class="card">

        <div class="card-body ">
            <div class="row">
                <div class="col-md-8">
                   <!--Google map-->
                    <div id="map-container" class="z-depth-1" style="height: 500px"></div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>{{ object.nombre }}</h1>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <h2>Municipios: -{{ departamento.get_municipios.count }}-</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <h2>Corregimientos: -{{ departamento.get_corregimientos.count }}-</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <h2>Votos: -{{ departamento.votantes.count }}-</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div align="center"><a href="{{ departamento.get_corregimientos_url }}"
                                                   class="btn bgm-purple waves-effect">Ver Corregimientos </a></div>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <div align="center"><a href="{% url 'geodata:departamentos' %}"
                                                   class="btn bgm-purple waves-effect">Volver a Departamentos </a></div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


        {% for municipio in municipio_list %}
            {% if forloop.first %}
                <div class="row">
            {% endif %}
            <div class="col-md-3">
                <!-- Blog Posts -->
                <div class="card blog-post">
                    <a class="card-header ch-alt" href="{{ municipio.get_lista_votantes_municipio_url }}">
                        <h2>{{ municipio.nombre|truncatechars:15 }}</h2>
                        <h5>corregimientos : {{ municipio.get_corregimientos.count }}</h5>
                        <h5>Cantidad de votos {{ municipio.cantidad_votantes }}</h5>
                    </a>
                </div>
            </div>
           {% if forloop.counter|divisibleby:4 %}
            </div>
            <div class="row">
        {% endif %}
        {% if forloop.last %}
            </div>
        {% endif %}
        {% endfor %}
        {% include 'utils/paginator.html' %}

    </div>
{% endblock %}


{% block scripts %}
    {% load staticfiles %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.css">


    <script>
        var map;
        function initMap() {
            map = new google.maps.Map(document.getElementById('map-container'), {
                zoom: 6,
                center: {lat: 3.8519738, lng: -73.6671921}
            });

            // NOTE: This uses cross-domain XHR, and may not work on older browsers.
            map.data.loadGeoJson(
                'http://localhost:8000/api/geodata/viewsets/departamentos/'+{{ departamento.id }}+'/?format=json');
            map.data.setStyle({
                fillColor: 'red',
                strokeWeight: 1
            });
            map.addListener('click', showArrays);
        }

        /** @this {google.maps.Polygon} */
        function showArrays(event) {
            // Since this polygon has only one path, we can call getPath() to return the
            // MVCArray of LatLngs.
            var vertices = this.getPath();

            var contentString = '<b>Departamento de {{ departamento.nombre }}</b><br>' +
                'Ubicacion: <br>' + event.latLng.lat() + ',' + event.latLng.lng() +
                '<br>';

            // Iterate over the vertices.
            for (var i = 0; i < vertices.getLength(); i++) {
                var xy = vertices.getAt(i);
                contentString += '<br>' + 'Coordenadas ' + i + ':<br>' + xy.lat() + ',' +
                    xy.lng();
            }

            // Replace the info window's content and position.
            infoWindow.setContent(contentString);
            infoWindow.setPosition(event.latLng);

            infoWindow.open(map);
        }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCZKP0IwBnUJ7zh_384tkLqlMMZF0B-vY4&callback=initMap">
    </script>


{% endblock %}