apps/main/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.InicioView.as_view(), name='inicio'),
    url(r'^login/', views.log_in, name='entrar'),
    url(r'^salir/', views.salir, name='salir'),

]

apps/third_party_apps/fcm/urls.py
from django.conf.urls import url

from . import views

urlpatterns = (
    url(r'^devices/$', views.DeviceList.as_view(), name='device_list'),
    url(r'^devices/(?P<pk>[0-9]+)/$', views.DeviceDetail.as_view(),
        name='device_detail'),
    url(r'^send/$', views.FCMList.as_view(), name='fcm_send'),
)

apps/votantes/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^votantes/',
        views.VotanteListView.as_view(),
        name='votantes'),

    url(r'^digitacion_rapida/',
        views.DigitacionRapidaView.as_view(),
        name='digitacion_rapida'),

    url(r'^cargue_masivo/',
        views.CargueMasivoView.as_view(),
        name='cargue_masivo'),

    url(r'^estadistica_campaña/',
        views.EstadisticaView.as_view(),
        name='estadistica_campaña'),

    url(r'^filtro_rapido/',
        views.FiltroRapidoListView.as_view(),
        name='filtro_rapido'),

    url(r'^perfil_votante/(?P<pk>\d+)/',
        views.PerfilVotanteView.as_view(),
        name='perfil_votante'),

    url(r'^crear_supervisor/',
        views.SupervisorCreateView.as_view(),
        name='crear_supervisor'),

    url(r'^lista_supervisores/',
        views.SupervisorListView.as_view(),
        name='lista_supervisores'),

    url(r'^crear_digitador/',
        views.DigitadorCreateView.as_view(),
        name='crear_digitador'),

    url(r'^lista_digitadores/',
        views.DigitadorListView.as_view(),
        name='lista_digitadores'),

    url(r'^call_center/',
        views.CallCenterListView.as_view(),
        name='call_center'),

    url(r'^generar_reporte/',
        views.GenerarReporteTemplateView.as_view(),
        name='generar_reporte'),

    url(r'^total_votantes_modificados/',
        views.TotalVotantesModificadosListView.as_view(),
        name='votantes_modificados'),


    url(r'^busqueda_facil/',
        views.BusquedaFacilListView.as_view(),
        name='busqueda_facil'),

    url(r'^reporte_votantes_modificados/',
        views.generar_reporte_votantes_modificados,
        name='reporte_votantes_modificados'),

    url(r'^auditoria_db/',
        views.AuditoriadbTemplateView.as_view(),
        name='auditoria_db'),

    url(r'^perfil_digitador/(?P<pk>\d+)/',
        views.DigitadorDetailView.as_view(),
        name='perfil_digitador')


]

project/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from .settings import base
from django.contrib import admin
from apps.utils import errors
from .settings import local

urlpatterns = [

    url(r'^elixir_master/', admin.site.urls),
    #frameworks and plugins
    # smart selects
    url(r'^chaining/', include('smart_selects.urls')),
    # rest auth
    url(r'^rest-auth/', include('rest_auth.urls')),
    # fcm
    url(r'^fcm/', include('apps.third_party_apps.fcm.urls')),
    # api
    url(r'^api/', include('apps.api.urls', namespace='api')),
    # apps 
    url(r'^app/', include('apps.app.urls', namespace='app')),
    url(r'^', include('apps.main.urls', namespace='main')),
    url(r'^geodata/', include('apps.geodata.urls', namespace='geodata')),
    url(r'^votantes/', include('apps.votantes.urls', namespace='votantes')),
    url(r'^reportes/', include('apps.reportes.urls', namespace='reportes')),
    

] + static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

if local.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

handler400 = errors.error400
handler403 = errors.error403
handler404 = errors.error404
handler500 = errors.error500

apps/main/models.py
from django.db import models
from datetime import datetime

from django.db.models import Q


class LogVotante(models.Model):
    usuario = models.ForeignKey('auth.User')
    votante = models.ForeignKey('votantes.Votante')
    accion = models.CharField(max_length=255)
    creacion = models.DateTimeField(auto_now_add=True)
    detalles = models.TextField(blank=True, null=True)
    ip = models.CharField(max_length=255, blank=True, null=True)
    llamada = models.BooleanField(default=False)
    no_volver_a_contactar = models.BooleanField(default=False)
    no_contesto = models.BooleanField(default=False)
    celular_equivocado = models.BooleanField(default=False)
    celular_apagado = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Cambio Votante'
        verbose_name_plural = 'Cambios Votantes'

    def votante_info(self):
        return '{} , cc: {}, {} - {}'.format(
            self.votante.nombre,
            self.votante.cedula,
            self.votante.municipio,
            self.votante.departamento
        )

    @staticmethod
    def get_date(date):
        return datetime.strptime(date, '%Y-%m-%d')

    @classmethod
    def get_llamadas_from_date(cls, date):
        date = cls.get_date(date)

        return cls.objects.filter(
            Q(no_contesto=True) |
            Q(celular_apagado=True) |
            Q(llamada=True) |
            Q(no_volver_a_contactar=True) |
            Q(celular_equivocado=True),
            creacion__day=date.day,
            creacion__month=date.month,
            creacion__year=date.year
        ).exclude(
            no_contesto=False,
            celular_apagado=False,
            llamada=False,
            no_volver_a_contactar=False,
            celular_equivocado=False
        )

    @classmethod
    def get_llamadas_contestadas_form_date(cls, date):
        date = cls.get_date(date)
        return cls.objects.filter(
            creacion__day=date.day,
            creacion__month=date.month,
            creacion__year=date.year,
            llamada=True
        ).exclude(
            no_contesto=False,
            celular_apagado=False,
            llamada=False,
            no_volver_a_contactar=False,
            celular_equivocado=False
        ).count()

    @classmethod
    def get_llamadas_no_contestadas_form_date(cls, date):
        date = cls.get_date(date)
        return cls.objects.filter(
            creacion__day=date.day,
            creacion__month=date.month,
            creacion__year=date.year,
            no_contesto=True
        ).exclude(
            no_contesto=False,
            celular_apagado=False,
            llamada=False,
            no_volver_a_contactar=False,
            celular_equivocado=False
        ).count()

    @classmethod
    def get_no_volver_a_llamar_form_date(cls, date):
        date = cls.get_date(date)
        return cls.objects.filter(
            creacion__day=date.day,
            creacion__month=date.month,
            creacion__year=date.year,
            no_volver_a_contactar=True
        ).exclude(
            no_contesto=False,
            celular_apagado=False,
            llamada=False,
            no_volver_a_contactar=False,
            celular_equivocado=False
        ).count()

    @classmethod
    def get_celular_equivocado_form_date(cls, date):
        date = cls.get_date(date)
        return cls.objects.filter(
            creacion__day=date.day,
            creacion__month=date.month,
            creacion__year=date.year,
            celular_equivocado=True
        ).exclude(
            no_contesto=False,
            celular_apagado=False,
            llamada=False,
            no_volver_a_contactar=False,
            celular_equivocado=False
        ).count()

    @classmethod
    def get_celular_apagado_form_date(cls, date):
        date = cls.get_date(date)
        return cls.objects.filter(
            creacion__day=date.day,
            creacion__month=date.month,
            creacion__year=date.year,
            celular_apagado=True
        ).exclude(
            no_contesto=False,
            celular_apagado=False,
            llamada=False,
            no_volver_a_contactar=False,
            celular_equivocado=False
        ).count()

apps/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime

from django.db.models import Q
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout, login as auth_login
from django.shortcuts import render, redirect
from apps.geodata.models import Departamento, Municipio, Corregimiento
from apps.utils.security import DigitadorLockAccessTimeMixin
from apps.utils.views import BaseTemplateView
from apps.votantes.models import Votante


def log_in(request):
    context = {'error': False}
    time_error = False
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if hasattr(user, 'digitador'):
            now = datetime.datetime.now()
            hora_entrada = now.replace(hour=7, minute=30, second=0, microsecond=0)
            hora_salida = now.replace(hour=20, minute=0, second=0, microsecond=0)
            if now <= hora_entrada or now >= hora_salida:
                logout(request)
                user = None
                time_error = True
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return redirect('main:inicio')
            else:
                context = {'msj': _('El usuario ha sido desactivado'), 'error': True}
        else:
            if time_error:
                context = {
                    'msj': _('su ingreso no esta permitido a esta hora'),
                    'error': True,
                    'warning': True
                }
            else:
                context = {'msj': _('usuario o contraseña incorrecta'), 'error': True}

    return render(request, 'login.html', context)


@login_required
def salir(request):
    logout(request)
    return redirect('main:entrar')


class InicioView(BaseTemplateView):
    template_name = 'apps/main/inicio.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['departamentos'] = Departamento.objects.all().count()
        context['municipios'] = Municipio.objects.all().count()
        context['corregimientos'] = Corregimiento.objects.all().count()
        context['votos'] = Votante.objects.filter(
            Q(duplicado=None) | Q(duplicado=False)
        ).exclude(
            Q(cedula__isnull=True) | Q(cedula__exact='')
        ).count()
        return context

templates/apps/main/inicio.html
{% extends 'index.html' %}
{% block titulo %}
    {% load staticfiles %}
{% endblock %}

{% block head_actions %}
 <li class="hidden-xs">
                    <button class="btn bgm-green waves-effect">DEPARTAMENTOS: {{ departamentos }}</button>
                </li>

                 <li class="hidden-xs">
                    <button class="btn bgm-purple waves-effect">MUNICIPIOS: {{ municipios }}</button>
                </li>

                <li class="hidden-xs">
                    <button class="btn bgm-lightblue waves-effect">CORREGIMIENTOS: {{ corregimientos }}</button>
                </li>

                <li class="hidden-xs">
                    <button class="btn bgm-pink waves-effect">VOTANTES : {{ votos }}</button>
                </li>
{% endblock %}

{% block main %}
    <div class="container">

        <div class="row">
            <div class="col-md-5 hidden-xs">
                <div class="card">
                    <div id="map-container" class="z-depth-1" style="height: 707px"></div>
                </div>
            </div>
            <div class="col-md-7">

                <div class="row">
                    <div class="col-md-6">
                        <!-- Blog Posts -->
                        <div class="card blog-post">
                            <img src="{% static 'img/demo/call-center.jpg' %} " class="img-responsive" alt="">

                            <a class="card-header ch-alt" href="#">
                             <div align="center"><h4>CALL CENTER </h4></div>

                            </a>

                            <div class="card-body card-padding">

                                <div align="center">
                                    <a href="{% url 'votantes:filtro_rapido' %}" class="btn bgm-green waves-effect">Entrar  <i class="zmdi zmdi-arrow-forward"></i></a>
                                </div>

                            </div>
                        </div>
                    </div>
                     <div class="col-md-6">
                        <!-- Blog Posts -->
                        <div class="card blog-post">
                            <img src="{% static 'img/demo/digitacion-rapida.jpg' %} " class="img-responsive" alt="">

                            <a class="card-header ch-alt" href="#">
                             <div align="center"><h4>DIGITACION RAPIDA </h4></div>

                            </a>

                            <div class="card-body card-padding">

                                <div align="center">
                                    <a href="{% url 'votantes:digitacion_rapida'  %}" class="btn bgm-green waves-effect">Entrar  <i class="zmdi zmdi-arrow-forward"></i></a>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>

                <div class="row">

                      <div class="col-md-6">
                        <!-- Blog Posts -->
                        <div class="card blog-post">
                            <img src="{% static 'img/demo/estadisticas.jpg' %} " class="img-responsive" alt="">

                            <a class="card-header ch-alt" href="#">
                                <div align="center"><h4><i class="zmdi zmdi-chart-donut"></i> ESTADISTICAS</h4></div>

                            </a>

                            <div class="card-body card-padding">


                                 <div align="center">
                                    <a href="{% url 'votantes:estadistica_campaña'  %}" class="btn bgm-green waves-effect">Entrar  <i class="zmdi zmdi-arrow-forward"></i></a>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <!-- Blog Posts -->
                        <div class="card blog-post">
                            <img src="{% static 'img/demo/filtro-rapido.jpg' %} " class="img-responsive" alt="">

                            <a class="card-header ch-alt" href="#">
                             <div align="center"><h4>FILTRO RAPIDO </h4></div>

                            </a>

                            <div class="card-body card-padding">

                                <div align="center">
                                    <a href="{% url 'votantes:filtro_rapido'  %}" class="btn bgm-green waves-effect">Entrar  <i class="zmdi zmdi-arrow-forward"></i></a>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>




            </div>
        </div>


    </div>
{% endblock %}

{% block scripts %}
    {% load staticfiles %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.css">


    <script>
        var map;
        function initMap() {
            map = new google.maps.Map(document.getElementById('map-container'), {
                zoom: 6,
                center: {lat: 3.8519738, lng: -73.6671921}
            });

        }

        /** @this {google.maps.Polygon} */
        function showArrays(event) {
            // Since this polygon has only one path, we can call getPath() to return the
            // MVCArray of LatLngs.
            var vertices = this.getPath();

            var contentString = '<b>Departamento de {{ departamento.nombre }}</b><br>' +
                'Ubicacion: <br>' + event.latLng.lat() + ',' + event.latLng.lng() +
                '<br>';

            // Iterate over the vertices.
            for (var i = 0; i < vertices.getLength(); i++) {
                var xy = vertices.getAt(i);
                contentString += '<br>' + 'Coordenadas ' + i + ':<br>' + xy.lat() + ',' +
                    xy.lng();
            }

            // Replace the info window's content and position.
            infoWindow.setContent(contentString);
            infoWindow.setPosition(event.latLng);

            infoWindow.open(map);
        }

    </script>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCZKP0IwBnUJ7zh_384tkLqlMMZF0B-vY4&callback=initMap">
    </script>


    <script>
        $(document).ready(function () {
            setTimeout(function () {
                notify("Bienvenidos a Elixir", "default")
            }, 1e3)
        });
    </script>


{% endblock %}