apps/geodata/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^subir-barrios/',
        views.BarriosUploadView.as_view(),
        name='subir_barrios'),

    url(r'^subir-corregimientos/',
        views.CorregimientosUploadView.as_view(),
        name='subir_corregimientos'),

    url(r'^subir-votantes/',
        views.VotanteUploadView.as_view(),
        name='subir_votante'),

    # origenes de datos

    url(r'^departamentos/',
        views.DepartamentoListView.as_view(),
        name='departamentos'),

    url(r'^detalle_departamento/(?P<pk>\d+)/',
        views.DepartamentoDetalleListView.as_view(),
        name='detalle_departamento'),

    url(r'^municipios_departamento/(?P<pk>\d+)/',
        views.MunicipioDepartamentoView.as_view(),
        name='municipios_departamento'),

    url(r'^corregimientos_departamento/(?P<pk>\d+)/',
        views.CorregimientosDepartamentoView.as_view(),
        name='corregimientos_departamento'
        ),

    url(r'^detalle_municipio/(?P<pk>\d+)/',
        views.MunicipioDetailView.as_view(),
        name='detalle_municipio'),

    url(r'^corregimientos_municipio/(?P<pk>\d+)/',
        views.CorregimientosMunicipioView.as_view,
        name='corregimientos_municipio'),

    url(r'^barrios_municipio/(?P<pk>\d+)/',
        views.BarriosMunicipio.as_view(),
        name='barrios_municipio'),

    url(r'^lista_votantes_municipio/(?P<pk>\d+)/',
        views.ListaVotantesMunicipioListView.as_view(),
        name='lista_votantes_municipio'),

    url(r'^lista_votantes_contactados_municipio/(?P<pk>\d+)/',
        views.VotantesContactadosMunicipioListView.as_view(),
        name='lista_votantes_contactados_municipio'),

    url(r'^lista_votantes_no_contactados_municipio/(?P<pk>\d+)/',
        views.VotantesNoContactadosMunicipioListView.as_view(),
        name='lista_votantes_no_contactados_municipio'),

]

apps/main/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.InicioView.as_view(), name='inicio'),
    url(r'^login/', views.log_in, name='entrar'),
    url(r'^salir/', views.salir, name='salir'),

]

apps/reportes/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^reporte_llamadas/',
        views.ReporteLLamadaTemplateView.as_view(),
        name='reporte_llamadas'),

    url(r'^reporte_votantes_nuevos/',
        views.ReporteVotantesNuevosFecha.as_view(),
        name='reporte_votantes_nuevos_fecha'),

    url(r'^reportes/',
        views.ReportesGeneradosListView.as_view(),
        name='reportes_generados')
]

apps/third_party_apps/fcm/urls.py
from django.conf.urls import url

from . import views

urlpatterns = (
    url(r'^devices/$', views.DeviceList.as_view(), name='device_list'),
    url(r'^devices/(?P<pk>[0-9]+)/$', views.DeviceDetail.as_view(),
        name='device_detail'),
    url(r'^send/$', views.FCMList.as_view(), name='fcm_send'),
)

apps/utils/urls.py
from django.conf.urls import url, include

urlpatterns = [

]

apps/votantes/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^votantes/',
        views.VotanteListView.as_view(),
        name='votantes'),

    url(r'^digitacion_rapida/',
        views.DigitacionRapidaView.as_view(),
        name='digitacion_rapida'),

    url(r'^cargue_masivo/',
        views.CargueMasivoView.as_view(),
        name='cargue_masivo'),

    url(r'^estadistica_campaña/',
        views.EstadisticaView.as_view(),
        name='estadistica_campaña'),

    url(r'^filtro_rapido/',
        views.FiltroRapidoListView.as_view(),
        name='filtro_rapido'),

    url(r'^perfil_votante/(?P<pk>\d+)/',
        views.PerfilVotanteView.as_view(),
        name='perfil_votante'),

    url(r'^crear_supervisor/',
        views.SupervisorCreateView.as_view(),
        name='crear_supervisor'),

    url(r'^lista_supervisores/',
        views.SupervisorListView.as_view(),
        name='lista_supervisores'),

    url(r'^crear_digitador/',
        views.DigitadorCreateView.as_view(),
        name='crear_digitador'),

    url(r'^lista_digitadores/',
        views.DigitadorListView.as_view(),
        name='lista_digitadores'),

    url(r'^call_center/',
        views.CallCenterListView.as_view(),
        name='call_center'),

    url(r'^generar_reporte/',
        views.GenerarReporteTemplateView.as_view(),
        name='generar_reporte'),

    url(r'^total_votantes_modificados/',
        views.TotalVotantesModificadosListView.as_view(),
        name='votantes_modificados'),


    url(r'^busqueda_facil/',
        views.BusquedaFacilListView.as_view(),
        name='busqueda_facil'),

    url(r'^reporte_votantes_modificados/',
        views.generar_reporte_votantes_modificados,
        name='reporte_votantes_modificados'),

    url(r'^auditoria_db/',
        views.AuditoriadbTemplateView.as_view(),
        name='auditoria_db'),

    url(r'^perfil_digitador/(?P<pk>\d+)/',
        views.DigitadorDetailView.as_view(),
        name='perfil_digitador')


]

project/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from .settings import base
from django.contrib import admin
from apps.utils import errors
from .settings import local

urlpatterns = [

    url(r'^elixir_master/', admin.site.urls),
    #frameworks and plugins
    # smart selects
    url(r'^chaining/', include('smart_selects.urls')),
    # rest auth
    url(r'^rest-auth/', include('rest_auth.urls')),
    # fcm
    url(r'^fcm/', include('apps.third_party_apps.fcm.urls')),
    # api
    url(r'^api/', include('apps.api.urls', namespace='api')),
    # apps 
    url(r'^app/', include('apps.app.urls', namespace='app')),
    url(r'^', include('apps.main.urls', namespace='main')),
    url(r'^geodata/', include('apps.geodata.urls', namespace='geodata')),
    url(r'^votantes/', include('apps.votantes.urls', namespace='votantes')),
    url(r'^reportes/', include('apps.reportes.urls', namespace='reportes')),
    

] + static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

if local.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

handler400 = errors.error400
handler403 = errors.error403
handler404 = errors.error404
handler500 = errors.error500

apps/utils/models.py
from django.db import models
from apps.third_party_apps.fcm.models import Device
from .apps import APP_NAME
from apps.utils import shortcuts as objects_
from django.contrib.auth.base_user import BaseUserManager

# Create your models here.

class BaseAppModel(models.Model):
    APP_NAME = APP_NAME

    class Meta:
        abstract = True


class HotelGranMaleconQueryset(models.QuerySet):

    def archive(self):
        return self.filter(archive=True)

    def all_unarchived(self):
        return self.filter(archive=False)


class HotelGranMaleconModelManager(BaseUserManager):
    def get_queryset(self):
        return HotelGranMaleconQueryset(self.model, using=self._db)

    def archive(self):
        return self.get_queryset().archive().order_by('-id')

    def all_unarchived(self):
        return self.get_queryset().all_unarchived().order_by('-id')


class BaseHotelGranMaleconModel(BaseAppModel):
    model_prefix = 'model'
    created = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    archive = models.BooleanField(default=False, editable=False)
    objects = HotelGranMaleconModelManager()

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def mark_as_archive(self):
        self.archive = True
        self.save()

    def get_kwargs(self):
        return {
            'pk': self.pk
        }

    def get_base_url(self, action):
        return reverse_lazy('{}:{}_{}'.format(
            self.APP_NAME, action, self.model_prefix
        ), kwargs=self.get_kwargs())

    def get_absolute_url(self):
        return self.get_base_url('detail')

    def get_update_url(self):
        return self.get_base_url('update')

    def get_archive_url(self):
        return self.get_base_url('archive')

    @classmethod
    def get_create_url(cls):
        return reverse_lazy('{}:create_{}'.format(
            cls.APP_NAME,
            cls.model_prefix
        ))

    @classmethod
    def get_list_url(cls):
        return reverse_lazy('{}:list_{}'.format(
            cls.APP_NAME,
            cls.model_prefix
        ))

    def get_time(self, time):
        return time.strftime("%I:%M %p")

    def get_date(self, date):
        locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
        return date.strftime('%d de %B de %Y')


class PushNotification(object):

    titulo = None
    motivo = None

    def send_push_notification(self, titulo, motivo):
    	self.titulo = titulo
    	self.motivo = motivo
        for device in Device.objects.all():
            device.send_message(self.get_notification_data())

    def get_notification_data(self):
        return {
            "notification": {
                "title": "{}".format(self.titulo),
                "body": "{}".format(self.motivo)
            }
        }

apps/utils/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class BaseUserCreationForm(UserCreationForm):
    form_title = None
    #email = forms.EmailField(label=_('email address'))

    class Meta:
        model = User
        exclude = (
            'last_login',
            'is_staff',
            'is_superuser',
            'date_joined',
            'groups',
            'user_permissions',
            'password',
            'is_active',
            'email'
        )
        fields = '__all__'


class FormAllFields(forms.ModelForm):

    form_title = 'None'

    class Meta:
        model = None
        fields = '__all__'

apps/utils/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import UpdateView, DetailView

from apps.utils.security import DigitadorLockAccessTimeMixin
from apps.utils.shortcuts import get_object_or_none


class BaseListView(LoginRequiredMixin, DigitadorLockAccessTimeMixin, ListView):
    pass


class BaseCreateView(LoginRequiredMixin, DigitadorLockAccessTimeMixin, CreateView):
    template_name = 'utils/forms/baseForm.html'

    def get_context_data(self, **kwargs):
        context = super(BaseCreateView, self).get_context_data(**kwargs)
        context['action'] = 'Crear'
        return context


class BaseListViewDinamicHeader(LoginRequiredMixin, DigitadorLockAccessTimeMixin, ListView):
    context_object_name = "list"
    query_fields = ()
    HEADER = None

    def __init__(self):
        super(BaseListViewDinamicHeader, self).__init__()
        self.HEADER += ('Acciones',)

    def get_queryset(self):
        return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super(BaseListViewDinamicHeader, self).get_context_data(**kwargs)
        context['header_table'] = self.get_header_table()
        return context

    def get_header_table(self):
        return self.HEADER


class DirectDeleteMixin(object):
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class BaseUpdateView(LoginRequiredMixin, DigitadorLockAccessTimeMixin, UpdateView):
    template_name = 'utils/forms/baseFor,m.html'

    def get_context_data(self, **kwargs):
        context = super(BaseUpdateView, self).get_context_data(**kwargs)
        context['action'] = 'Modificar'
        return context

    def get_object(self, queryset=None):
        obj = self.model.objects.get(id=self.kwargs['pk'])
        return obj


class BaseTemplateView(LoginRequiredMixin, DigitadorLockAccessTimeMixin, TemplateView):
    pass


class BaseDetailView(LoginRequiredMixin, DigitadorLockAccessTimeMixin, DetailView):
    pass

templates/utils/menu.html
{% load staticfiles %}
<ul class="main-menu">
    <li class="mm-profile sub-menu">
        <a href="" data-ma-action="submenu-toggle" class="media">
            <img class="pull-left" src="{% static 'img/profile-pics/2.jpg' %}" alt="">
            <div class="media-body">
                {{ user.get_full_name }}
                <small>{{ user.username }}</small>
            </div>
        </a>

        <ul>
            <li class="hidden">
                <a href="">Ver mis estadisticas</a>
            </li>

            {% if user.is_superuser %}
                <li>
                    <a href="{% url 'admin:index' %}">
                        Administrador <i class="fa fa-bug"></i>
                    </a>
                </li>
            {% endif %}

            <li>
                <a href="{% url 'main:salir' %}">Salir</a>
            </li>
        </ul>
    </li>

    <li>
        <a href="{% url 'main:inicio' %}">
            <i class="zmdi zmdi-home"></i>
            Inicio
        </a>
    </li>
    <li>
        <a href="{% url 'geodata:departamentos' %}">
            <i class="zmdi zmdi-google-maps"></i>
            Departamentos
        </a>
    </li>

    <li>
        <a href="{% url 'votantes:digitacion_rapida' %}">
            <i class="zmdi zmdi-keyboard"></i>
            Digitacion rapida
        </a>
    </li>


    <li>
        <a href="{% url 'votantes:filtro_rapido' %}">
            <i class="zmdi zmdi-filter-list"></i>
            Filtro rapido
        </a>
    </li>

    <li class="sub-menu">
        <a href="" data-ma-action="submenu-toggle">
            <i class="zmdi zmdi-chart-donut"></i>
            Reportes
        </a>

        <ul>
            <li>
                 <a href="{% url 'reportes:reportes_generados' %}">
                     <i class="zmdi zmdi-notifications-active"></i>
                     Reportes generados
                 </a>
            </li>
            <li>
                 <a href="{% url 'votantes:generar_reporte' %}">
                     <i class="zmdi zmdi-account"></i>
                     Votantes
                 </a>
            </li>
            <li>
                <a href="{% url 'reportes:reporte_llamadas' %}">
                    <i class="zmdi zmdi-phone-forwarded"></i>
                    Llamadas
                </a>
            </li>
            <li>
                <a href="{% url 'reportes:reporte_votantes_nuevos_fecha' %}">
                    <i class="zmdi zmdi-plus"></i>
                    Nuevos por rango de fecha
                </a>
            </li>
        </ul>

    </li>

    {% if request.user.is_superuser %}
        <li class="sub-menu">
            <a href="" data-ma-action="submenu-toggle">
                <i class="zmdi zmdi-mood"></i>
                Supervisores
            </a>

            <ul>
                <li><a href="{% url 'votantes:crear_supervisor' %}">Crear Supervisor</a></li>
                <li><a href="{% url 'votantes:lista_supervisores' %}">Lista de Supervisores</a></li>
            </ul>
        </li>
    {% endif %}


    {% if request.user.is_superuser or request.user.supervisor %}
        <li class="sub-menu">
            <a href="" data-ma-action="submenu-toggle">
                <i class="zmdi zmdi-edit"></i>
                Digitadores
            </a>

            <ul>
                <li>
                    <a href="{% url 'votantes:crear_digitador' %}">
                        Crear Digitador
                    </a>
                </li>
                <li>
                    <a href="{% url 'votantes:lista_digitadores' %}">
                        Lista de Digitadores
                    </a>
                </li>
            </ul>
        </li>
    {% endif %}


    <li class="sub-menu">
        <a href="" data-ma-action="submenu-toggle">
            <i class="zmdi zmdi-favorite"></i>
            Votantes
        </a>

        <ul>
            <li>
                <a href="{% url 'votantes:votantes_modificados' %}">
                    <i class="zmdi zmdi-time-restore"></i> Actualizados
                </a>
            </li>

            <li>
                <a href="{% url 'votantes:busqueda_facil' %}">
                    <i class="zmdi zmdi-search"></i>
                    Busqueda Facil
                </a>
            </li>
        </ul>

    </li>

    <li>
        <a href="{% url 'votantes:auditoria_db' %}">
            <i class="zmdi zmdi-filter-list"></i>
            Filtro Auditoria DB
        </a>
    </li>

</ul>

templates/utils/paginator.html
{% load i18n %}
<div class="row" align="center">
    <div class="col-md-12">
        <ul class="pagination center-block">
            {% if page_obj.has_previous %}
                 <li>
                    <a href="?page={{ page_obj.previous_page_number }}">
                        <i class="zmdi zmdi-chevron-left"></i>
                    </a>
                 </li>
            {% else %}
                <li class="previous first disabled">
                    <a class="a-prevent">
                        <i class="zmdi zmdi-chevron-left"></i>
                    </a>
                </li>
            {% endif %}
            {% for page in page_obj.pages %}
                {% if page %}
                    {% ifequal page page_obj.number %}
                        <li class="active">
                            <span class="current page">{{ page }}</span>
                        </li>
                    {% else %}
                       <li>
                         <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                       </li>
                    {% endifequal %}
                {% else %}
                    <li class="previous first disabled">
                        <a class="a-prevent" href="">
                            <i class="zmdi zmdi-more-horiz"></i>
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li>
                    <a href="?{{ page_obj.next_page_number.querystring }}" class="next">
                       <i class="zmdi zmdi-chevron-right"></i>
                    </a>
                </li>
            {% else %}
                <li class="next disabled">
                    <a class="a-prevent">
                        <i class="zmdi zmdi-chevron-right"></i>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>